name: Build Android

on:
  workflow_call:
    inputs:
      version:
        description: "tag name"
        required: false
        type: string

jobs:
  build-android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup build environment
        id: setup
        uses: ./.github/actions/setup
        with:
          version: ${{ inputs.version }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Decode Keystore
        run: |
          mkdir -p android/keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/keystore/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo 'storePassword=${{ secrets.KEYSTORE_PASSWORD }}' > android/key.properties
          echo 'keyPassword=${{ secrets.KEY_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=${{ secrets.KEY_ALIAS }}' >> android/key.properties
          echo 'storeFile=../keystore/upload-keystore.jks' >> android/key.properties

      - name: Build APK
        run: |
          flutter build apk --release --split-per-abi \
            --obfuscate --split-debug-info=build/app/outputs/symbols \
            --dart-define=GIT_TAG=${{ steps.setup.outputs.GIT_TAG }} \
            --dart-define=GIT_COMMIT=${{ steps.setup.outputs.GIT_COMMIT }} \
            --dart-define=GIT_COMMIT_DATE=${{ steps.setup.outputs.GIT_COMMIT_DATE }} \
            --dart-define=BUILD_TIME=${{ steps.setup.outputs.BUILD_TIME }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/*.apk
